package siris.ontology.types

import siris.ontology.{SVarDescription, Symbols}



object Acceleration extends SVarDescription( siris.ontology.types.Vector3 as Symbols.acceleration )
object AccelerationFactor extends SVarDescription( siris.ontology.types.Real as Symbols.accelerationFactor )
object Alignment extends SVarDescription( siris.ontology.types.Enumeration as Symbols.alignment )
object Angle extends SVarDescription( siris.ontology.types.Real as Symbols.angularFactor )
object AngularDamping extends SVarDescription( siris.ontology.types.Real as Symbols.angularDamping )
object AngularFactor extends SVarDescription( siris.ontology.types.Real as Symbols.angularFactor )
object AnyList extends SVarDescription[scala.collection.immutable.List[_], scala.collection.immutable.List[_]]( siris.ontology.types.NullType as Symbols.anyList createdBy(Nil) )
object AttractorAttractionFactor extends SVarDescription( siris.ontology.types.Real as Symbols.attractorAttractionFactor )
object AttractorStrength extends SVarDescription( siris.ontology.types.Integer as Symbols.attractorStrength )

object BackTexture extends SVarDescription( siris.ontology.types.String as Symbols.backTexture )
object Boolean extends SVarDescription[scala.Boolean, scala.Boolean]( siris.ontology.types.NullType as Symbols.boolean createdBy(false) )
object BoundingBox extends SVarDescription[siris.core.helper.BoundingBox, siris.core.helper.BoundingBox]( siris.ontology.types.NullType as Symbols.boundingBox createdBy(siris.core.helper.BoundingBox(simplex3d.math.floatm.Vec3f.Zero, simplex3d.math.floatm.Vec3f.One)) )
object Button_Center extends SVarDescription( siris.ontology.types.Boolean as Symbols.button_Center )
object Button_Left extends SVarDescription( siris.ontology.types.Boolean as Symbols.button_Left )
object Button_Right extends SVarDescription( siris.ontology.types.Boolean as Symbols.button_Right )

object CollisionGroup extends SVarDescription[scala.Short, scala.Short]( siris.ontology.types.NullType as Symbols.collisionGroup createdBy(0.toShort) )
object CollidesWith extends SVarDescription[scala.Short, scala.Short]( siris.ontology.types.NullType as Symbols.collidesWith createdBy(0.toShort) )
object CastShadow extends SVarDescription( siris.ontology.types.Boolean as Symbols.castShadow )
object ColladaFile extends SVarDescription( siris.ontology.types.String as Symbols.colladaFile )
object ColladaObjectId extends SVarDescription( siris.ontology.types.String as Symbols.colladaObjectId )
object Color extends SVarDescription[java.awt.Color, java.awt.Color]( siris.ontology.types.NullType as Symbols.color createdBy(java.awt.Color.WHITE) )
object Configuration extends SVarDescription( siris.ontology.types.NamedContainer as Symbols.configuration )
object ConstantAttenuation extends SVarDescription( siris.ontology.types.Real as Symbols.constantAttenuation )
object Container extends SVarDescription[siris.core.entity.description.SValList, siris.core.entity.description.SValList]( siris.ontology.types.NullType as Symbols.container createdBy(new siris.core.entity.description.SValList()) )

object DiffuseColor extends SVarDescription( siris.ontology.types.Color as Symbols.diffuseColor )
object Direction extends SVarDescription( siris.ontology.types.Vector3 as Symbols.direction )
object DownTexture extends SVarDescription( siris.ontology.types.String as Symbols.downTexture )
object DrawLines extends SVarDescription( siris.ontology.types.Boolean as Symbols.drawLines )

object Entity extends SVarDescription[siris.core.entity.Entity, siris.core.entity.Entity]( siris.ontology.types.NullType as Symbols.entity createdBy(new siris.core.entity.Entity) )
object Enumeration extends SVarDescription[siris.ontology.types.TypeDefinitions.Enum, siris.ontology.types.TypeDefinitions.Enum]( siris.ontology.types.NullType as Symbols.enumeration createdBy(siris.ontology.types.DefaultEnum.Foo) )
object EventDescription extends SVarDescription[siris.components.eventhandling.EventDescription, siris.components.eventhandling.EventDescription]( siris.ontology.types.NullType as Symbols.eventDescription createdBy(new siris.components.eventhandling.EventDescription(siris.ontology.Symbols.nullType)) )

object Factor extends SVarDescription( siris.ontology.types.Real as Symbols.factor )
object FarClip extends SVarDescription( siris.ontology.types.Real as Symbols.farClip )
object File extends SVarDescription( siris.ontology.types.String as Symbols.file )
object Frame extends SVarDescription[Any, Any]( siris.ontology.types.NullType as Symbols.frame createdBy(null.asInstanceOf[Any]) )
object FrontTexture extends SVarDescription( siris.ontology.types.String as Symbols.frontTexture )

object Gravity extends SVarDescription( siris.ontology.types.Vector3 as Symbols.gravity )

object HalfExtends extends SVarDescription( siris.ontology.types.Vector3 as Symbols.halfExtends )
object HeadTransform extends SVarDescription( siris.ontology.types.Matrix as Symbols.headTransform )
object Health extends SVarDescription( siris.ontology.types.Real as Symbols.health )
object Height extends SVarDescription( siris.ontology.types.Real as Symbols.height )

object Identifier extends SVarDescription[scala.Symbol, scala.Symbol]( siris.ontology.types.NullType as Symbols.identifier createdBy(Symbol("")) )
object Impulse extends SVarDescription( siris.ontology.types.Vector3 as Symbols.impulse )
object Initialize extends SVarDescription( siris.ontology.types.Boolean as Symbols.initialize )
object Integer extends SVarDescription[scala.Int, scala.Int]( siris.ontology.types.NullType as Symbols.integer createdBy(0) )
object Intensity extends SVarDescription( siris.ontology.types.Real as Symbols.intensity )
object Interactions extends SVarDescription( siris.ontology.types.AnyList as Symbols.interactions )
object Ip extends SVarDescription( siris.ontology.types.String as Symbols.ip )

object Key_Down extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_Down )
object Key_Left extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_Left )
object Key_Right extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_Right )
object Key_Space extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_Space )
object Key_Up extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_Up )
object Key_a extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_a )
object Key_b extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_b )
object Key_c extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_c )
object Key_d extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_d )
object Key_e extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_e )
object Key_f extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_f )
object Key_g extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_g )
object Key_h extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_h )
object Key_i extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_i )
object Key_j extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_j )
object Key_k extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_k )
object Key_l extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_l )
object Key_m extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_m )
object Key_n extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_n )
object Key_o extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_o )
object Key_p extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_p )
object Key_q extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_q )
object Key_r extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_r )
object Key_s extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_s )
object Key_t extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_t )
object Key_u extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_u )
object Key_v extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_v )
object Key_w extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_w )
object Key_x extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_x )
object Key_y extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_y )
object Key_z extends SVarDescription( siris.ontology.types.Boolean as Symbols.key_z )

object LeftTexture extends SVarDescription( siris.ontology.types.String as Symbols.leftTexture )
object LinearAttenuation extends SVarDescription( siris.ontology.types.Real as Symbols.linearAttenuation )
object LinearDamping extends SVarDescription( siris.ontology.types.Real as Symbols.linearDamping )
object Lives extends SVarDescription( siris.ontology.types.Integer as Symbols.lives )
object Long extends SVarDescription[scala.Long, scala.Long]( siris.ontology.types.NullType as Symbols.long createdBy(0L) )

object Mana extends SVarDescription( siris.ontology.types.Real as Symbols.mana )
object ManipulatorList extends SVarDescription( siris.ontology.types.AnyList as Symbols.manipulatorList )
object Mass extends SVarDescription( siris.ontology.types.Real as Symbols.mass createdBy(1f) )
object Matrix extends SVarDescription[simplex3d.math.floatm.renamed.Mat4x4, simplex3d.math.floatm.renamed.Mat4x4]( siris.ontology.types.NullType as Symbols.matrix createdBy(simplex3d.math.floatm.renamed.Mat4x4.Identity) )
object MaxAccMag extends SVarDescription( siris.ontology.types.Real as Symbols.maxAccMag )
object MaxAttractors extends SVarDescription( siris.ontology.types.Integer as Symbols.maxAttractors )
object MaxNeighbors extends SVarDescription( siris.ontology.types.Integer as Symbols.maxNeighbors )
object Mesh extends SVarDescription[Any, Any]( siris.ontology.types.NullType as Symbols.mesh createdBy(null.asInstanceOf[Any]) )
object MinAttractorDistance extends SVarDescription( siris.ontology.types.Real as Symbols.minAttractorDistance )
object MinDistanceToNeighbors extends SVarDescription( siris.ontology.types.Real as Symbols.minDistanceToNeighbors )
object MinDistanceToPredators extends SVarDescription( siris.ontology.types.Real as Symbols.minDistanceToPredators )

object Name extends SVarDescription( siris.ontology.types.String as Symbols.name )
object NamedContainer extends SVarDescription[siris.core.entity.description.NamedSValList, siris.core.entity.description.NamedSValList]( siris.ontology.types.NullType as Symbols.namedContainer createdBy(new siris.core.entity.description.NamedSValList(siris.ontology.Symbols.nullType)) )
object NearClip extends SVarDescription( siris.ontology.types.Real as Symbols.nearClip )
object Neighbor extends SVarDescription( siris.ontology.types.Entity as Symbols.neighbor )
object NeighborhoodAttractionFactor extends SVarDescription( siris.ontology.types.Real as Symbols.neighborhoodAttractionFactor )
object Normal extends SVarDescription( siris.ontology.types.Vector3 as Symbols.normal createdBy(simplex3d.math.floatm.renamed.Vec3(1,0,0)) )

object Origin extends SVarDescription( siris.ontology.types.Vector3 as Symbols.origin )

object ParentElement extends SVarDescription( siris.ontology.types.Entity as Symbols.parentElement )
object Port extends SVarDescription( siris.ontology.types.Integer as Symbols.port )
object Position extends SVarDescription( siris.ontology.types.Vector3 as Symbols.position )
object Position2D extends SVarDescription( siris.ontology.types.Vector2 as Symbols.position2D )
object PostProcessingEffect extends SVarDescription[siris.components.renderer.jvr.PostProcessingEffect, siris.components.renderer.jvr.PostProcessingEffect]( siris.ontology.types.NullType as Symbols.postProcessingEffect createdBy(new siris.components.renderer.jvr.PostProcessingEffect) )
object Probability extends SVarDescription( siris.ontology.types.Real as Symbols.probability )

object QuadraticAttenuation extends SVarDescription( siris.ontology.types.Real as Symbols.quadraticAttenuation )

object Radius extends SVarDescription( siris.ontology.types.Real as Symbols.radius )
object Real extends SVarDescription[scala.Float, scala.Float]( siris.ontology.types.NullType as Symbols.real createdBy(0f) )
object Restitution extends SVarDescription( siris.ontology.types.Real as Symbols.restitution )
object RightTexture extends SVarDescription( siris.ontology.types.String as Symbols.rightTexture )

object Saturation extends SVarDescription( siris.ontology.types.Real as Symbols.saturation )
object Scale extends SVarDescription( siris.ontology.types.Matrix as Symbols.scale )
object ScreenCoordinates extends SVarDescription[scala.collection.immutable.List[simplex3d.math.floatm.renamed.Vec2], scala.collection.immutable.List[simplex3d.math.floatm.renamed.Vec2]]( siris.ontology.types.NullType as Symbols.screenCoordinates createdBy(Nil) )
object ShadowBias extends SVarDescription( siris.ontology.types.Real as Symbols.shadowBias )
object ShowHeightMap extends SVarDescription( siris.ontology.types.Boolean as Symbols.showHeightMap )
object SimulationSpeed extends SVarDescription( siris.ontology.types.Real as Symbols.simulationSpeed )
object Size extends SVarDescription( siris.ontology.types.Real as Symbols.size )
object SkyBoxFog extends SVarDescription( siris.ontology.types.Real as Symbols.skyBoxFog )
object SpecularColor extends SVarDescription( siris.ontology.types.Color as Symbols.specularColor )
object SpotCutOff extends SVarDescription( siris.ontology.types.Real as Symbols.spotCutOff )
object SpotExponent extends SVarDescription( siris.ontology.types.Real as Symbols.spotExponent )
object String extends SVarDescription[java.lang.String, java.lang.String]( siris.ontology.types.NullType as Symbols.string createdBy("") )
object SubElement extends SVarDescription( siris.ontology.types.String as Symbols.subElement )

object Texture extends SVarDescription[Any, Any]( siris.ontology.types.NullType as Symbols.texture createdBy(null) )
object Thickness extends SVarDescription( siris.ontology.types.Real as Symbols.thickness )
object Threshold extends SVarDescription( siris.ontology.types.Real as Symbols.threshold )
object Transformation extends SVarDescription( siris.ontology.types.Matrix as Symbols.transformation )

object UpTexture extends SVarDescription( siris.ontology.types.String as Symbols.upTexture )
object UpVector extends SVarDescription( siris.ontology.types.Vector3 as Symbols.upVector )

object Vector2 extends SVarDescription[simplex3d.math.floatm.renamed.Vec2, simplex3d.math.floatm.renamed.Vec2]( siris.ontology.types.NullType as Symbols.vector2 createdBy(simplex3d.math.floatm.renamed.Vec2.Zero) )
object Vector3 extends SVarDescription[simplex3d.math.floatm.renamed.Vec3, simplex3d.math.floatm.renamed.Vec3]( siris.ontology.types.NullType as Symbols.vector3 createdBy(simplex3d.math.floatm.renamed.Vec3.Zero) )
object Vector4 extends SVarDescription[simplex3d.math.floatm.renamed.Vec4, simplex3d.math.floatm.renamed.Vec4]( siris.ontology.types.NullType as Symbols.vector4 createdBy(simplex3d.math.floatm.renamed.Vec4.Zero) )
object Velocity extends SVarDescription( siris.ontology.types.Vector3 as Symbols.velocity )
object ViewPlatform extends SVarDescription( siris.ontology.types.Matrix as Symbols.viewPlatform )

object WaveScale extends SVarDescription( siris.ontology.types.Real as Symbols.waveScale )